### ISSUE TITLE
Docs for Sentinel Server Pools

### ISSUE THREAD

**Issue by syamsathyan** [helifu/twemproxy-163#1]
Can you please add some more documentation

**Comment by helifu** [comment]
conf/nutcracker.yml

alpha:
  listen: 0.0.0.0:6379
  hash: murmur
  hash_tag: "{}"
  distribution: ketama
  timeout: 400
  redis_auth: 123456
  groups:
   - groups_helf_0
   - groups_helf_1
   - groups_helf_2
   - groups_helf_3
  sentinel_heartbeat: 2000
  sentinels:
   - 10.164.97.188:26379 sentinel0
   - 10.164.97.189:26379 sentinel1
   - 10.164.97.190:26379 sentinel2

**Comment by helifu** [comment]
ok, i have updated the 'readme.md' just now.
